
name: Post Deployment Workflow

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually
    inputs:
      build_id:
        description: "Commit ID to send to CICD Manager"
        required: true
        default: "cm/10/10"   

jobs:
  QualityGate-BuildPromotion-GitActionWorkflow:
    runs-on: ubuntu-latest

    steps:
      - name: Display a message
        run: echo "This workflow was triggered from GuideWire quality Gates!"

      - name: Show Buildid input
        run: echo "build_id input was ${{ github.event.inputs.build_id }}"

      - name: Run a script
        run: |
          echo "Running GuideWire Test cases."

      - name: Wait for 90 seconds
        run: sleep 90

      - name: Run a script
        run: |
          echo "All Test Cases passed successfully."    
     
      
