name: Quality Gate Workflow

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  run-manually:
    runs-on: ubuntu-latest

    steps:
      - name: Display a message
        run: echo "This workflow was triggered from GuideWire quality Gates!"

      - name: Run a script
        run: |
          echo "Running GuideWire Test cases."

      - name: Run a script
        run: |
          echo "All Test Cases passed successfully."
