name: Quality Gate Workflow

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually
    inputs:
      commit_id:
        description: "Commit ID to send to CICD Manager"
        required: true
        default: "eda36be13d2d54544f51a061d8c8b8203c59449e"   

jobs:
  run-manually:
    runs-on: ubuntu-latest

    steps:
      - name: Display a message
        run: echo "This workflow was triggered from GuideWire quality Gates!"

      - name: Show commitId input
        run: echo "CommitId input was ${{ github.event.inputs.commit_id }}"

      - name: Run a script
        run: |
          echo "Running GuideWire Test cases."

      - name: Wait for 90 seconds
        run: sleep 90

      - name: Run a script
        run: |
          echo "All Test Cases passed successfully."     
     
      - name: Call CICD Manager Quality Gate API
        run: |
          curl -X POST "https://cicd-manager-service.api.omega2-andromeda.guidewire.net/api/v3/tenants/valuemom/starsystems/gwcp/applications/cc/quality-gates/qualitygateswebhooktest/verifications" \
            -H "Authorization: Bearer ${{ secrets.CICD_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"artifact\": {
                \"type\": \"COMMIT\",
                \"id\": \"${{ github.event.inputs.commit_id }}\"
              },
              \"status\": \"SUCCESSFUL\",
              \"url\": \"https://bitbucket.example.com/browse/GWCP-0000\",
              \"comment\": \"Verification Passed from GitHub Actions\"
            }"
